Adjust dt-chef-solo to expect recent py on PATH

diff --git a/cookbooks/nimbus_context_agent/templates/default/dt-chef-solo b/cookbooks/nimbus_context_agent/templates/default/dt-chef-solo
--- a/cookbooks/nimbus_context_agent/templates/default/dt-chef-solo
+++ b/cookbooks/nimbus_context_agent/templates/default/dt-chef-solo
@@ -2,31 +2,37 @@
 
 # Assumes a script colocated in the same directory called dt-chef-solo.py
 
+
+PYEXE="python"
+EZEXE="easy_install"
+
+# DL: leaving this around as we may need same tricks for OOI centOS6 image
+
 # hack for OOI base image which doesn't have easy_install-2.5 in $PATH
 # where this script runs.
-if [ -d /opt/python2.5/bin ]; then
-    PATH="$PATH:/opt/python2.5/bin"
-fi
+#if [ -d /opt/python2.5/bin ]; then
+#    PATH="$PATH:/opt/python2.5/bin"
+#fi
 
-PYTHON1="python2.5"
-EZ1="easy_install-2.5"
-PYTHON2="python2.6"
-EZ2="easy_install-2.6"
+#PYTHON1="python2.5"
+#EZ1="easy_install-2.5"
+#PYTHON2="python2.6"
+#EZ2="easy_install-2.6"
 
-$PYTHON1 -c "import os"
-if [ $? -eq 0 ]; then
-    PYEXE=$PYTHON1
-    EZEXE=$EZ1
-else
-    $PYTHON2 -c "import os"
-    if [ $? -eq 0 ]; then
-        PYEXE=$PYTHON2
-        EZEXE=$EZ2
-    else
-        echo "Could not locate a working Python installation"
-        exit 1
-    fi
-fi
+#$PYTHON1 -c "import os"
+#if [ $? -eq 0 ]; then
+#    PYEXE=$PYTHON1
+#    EZEXE=$EZ1
+#else
+#    $PYTHON2 -c "import os"
+#    if [ $? -eq 0 ]; then
+#        PYEXE=$PYTHON2
+#        EZEXE=$EZ2
+#    else
+#        echo "Could not locate a working Python installation"
+#        exit 1
+#    fi
+#fi
 
 $PYEXE -c "import simplejson"
 if [ $? -ne 0 ]; then
