Output the end of the Chef log when the Chef Solo run fails

diff --git a/cookbooks/nimbus_context_agent/templates/default/dt-chef-solo b/cookbooks/nimbus_context_agent/templates/default/dt-chef-solo
--- a/cookbooks/nimbus_context_agent/templates/default/dt-chef-solo
+++ b/cookbooks/nimbus_context_agent/templates/default/dt-chef-solo
@@ -56,4 +56,10 @@ fi
 
 dir=`dirname $0`
 $PYEXE $dir/dt-chef-solo.py $1 &> /opt/dt-chef-solo.log
-exit $?
+CHEF_EXIT=$?
+
+# If Chef failed, output the end of the Chef log
+if [ $CHEF_EXIT != 0 ]; then
+  tail -100 /opt/dt-chef-solo.log
+fi
+exit $CHEF_EXIT
